### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by alek5k** [mml-book/mml-book.github.io#169] opened 2018-10-29 03:22 UTC
**Describe the mistake**
Spelling error - mappping 

**Location**
Chapter 4
Line 2229

**Proposed solution**
map mappping to mapping :)
Maybe running a spell checker through it will pick these sorts of things up?

**Comment by mpd37** [comment] 2018-10-29 09:13
duplicate of #104

**Closed as completed** 2019-02-05 13:23 UTC
Labels: Chapter 4
