### ISSUE TITLE
Inconsistent notation on page 177, Bayes Theorem

### ISSUE THREAD

**Issue by 1o0ko** [mml-book/mml-book.github.io#71] opened 2018-08-14 02:13 UTC
**Describe the mistake**
In line 3205 "p(x | y)"  is said to be the likelihood that describes how x and y are related, which is supported by the eq. (6.21)
In line 3207 "p(x | y)" is described as posterior. 

If the Bayes theorem is stated as:
```
p(y | x) = p(x | y) p(y) / p(x)
```
then, 
- p(y) is our prior
- p(y | x) is our posterior
- P(x | y) / p(x) loosely represents the support B provides for A.
**Location**
Please provide the 
1. Draft (2018-07-04)
2. Chapter 6
3. page 177
4. line 3207

**Proposed solution**
change lines: 3207, 3208 

"The posterior p(x | y) expresses exactly posterior what we know about x if we observe y" 
to 
"The posterior p(y | x) expresses exactly posterior what we know about y if we observe x" 

what we are interested in, i.e
**Additional context**

**Comment by mpd37** [comment] 2018-09-23 05:51
Duplicate of #70

**Comment by chengsoonong** [comment] 2018-10-12 04:29
We've reworded this section to tidy this up. Thanks.
Fixed in ab2f03527c40f9ea68a63c04f72605671b80652f

**Closed by chengsoonong** 2018-10-12 04:29 UTC
Labels: Chapter 6
