### ISSUE TITLE
2. Paragraph 1 of 3.7 Inner Product, page 80

### ISSUE THREAD

**Issue by vbartle** [mml-book/mml-book.github.io#532] opened 2020-05-14 23:12 UTC
2. Paragraph 1 of 3.7 Inner Product, page 80
**Describe the mistake**
“We can think of a vector x in rn as function” -> as *a* function.

**Location**
Please provide the 
1. version (bottom of page)  “Draft (2020-03-07) of “Mathematics for Machine Learning”. Feedback: https://mml-book.com. “
2. Chapter 3
3. page 80
4. line number/equation number paragraph 1 3.7 inner product

**Proposed solution**
“We can think of a vector x in rn as function” -> as *a* function.

**Additional context**
Also, Figure 3.7 on this same page states that w is orthogonal to U, but graphically it isn’t.

**Comment by mpd37** [comment] 2020-05-16 07:58
duplicate of #498

Regarding Figure 3.7: The red square in the figure should indicate that w is orthogonal to U. Note that U is not spanned by e_1 and e_2.

**Closed** 2020-05-16 07:58 UTC
Labels: Chapter 3
