### ISSUE TITLE
Introduction issues (Line 651)

### ISSUE THREAD

**Issue by fiono** [mml-book/mml-book.github.io#237] opened 2019-01-21 21:34 UTC
**Describe the mistake**
First sentence of the intro doesn't make sense.

**Location**
1. Draft (2018-12-24)
2. Chapter 1
3. Page 13
4. L651

**Proposed solution**
The first sentence ("Machine learning is about designing algorithms that automatically extract
valuable from data") doesn't seem to parse. Should it be "automatically extract value from data"?

Also the paragraph's last sentence (L656) is missing a "."

**Additional context**
Possible I'm just misreading!

**Comment by mpd37** [comment] 2019-01-21 21:37
Duplicate of #229

**Closed by mpd37** 2019-01-21 21:37 UTC
