### ISSUE TITLE
Tinyurl link to Gilbert Strang's course is broken

### ISSUE THREAD

**Issue by BartOMan** [mml-book/mml-book.github.io#758] opened 2023-09-10 16:51 UTC
The book contains a Tinyurl link to Gilbert Strang's course on Linear Algebra, and the link is broken.

The tinyurl resolves to the MIT OCW link below, but it's broken.
https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/resources/video-lectures/

Location:
The same link is in BOTH my paper copy AND in the online PDF, draft 2023-02-15, chapter 2, p18, in the margin notes.

**Comment by mpd37** [comment] 2023-09-20 21:15
Duplicate of #745

**Closed by mpd37** 2023-09-20 21:15 UTC
