### ISSUE TITLE
Do we have way to generate a pdf version which does not contain the line number on the left ?

### ISSUE THREAD

**Issue by zhfkt** [mml-book/mml-book.github.io#260] opened 2019-02-21 09:24 UTC
**Is your feature request related to a problem? Please describe.**

Do we have way to generate a pdf version which does not contain the line number on the left ?

I have a note taking app on the Ipad (Marginnote 3). When I copy the text from the PDF into the note APP, the  line number on the left will be always copied as well, which breaks the sentence. I am not sure whether it is a reasonable request.

Thank you !

**Comment by mpd37** [comment] 2019-02-21 09:41
Yes. Around mid March latest.


On Feb 21, 2019 at 09:24, <zhfkt<mailto:notifications@github.com>> wrote:


Is your feature request related to a problem? Please describe.

Do we have way to generate a pdf version which does not contain the line number on the left ?

I have a note taking app on the Ipad (Marginnote 3). When I copy the text from the PDF into the note APP, the line number on the left will be always copied as well, which breaks the sentence. I am not sure whether it is a reasonable request.

Thank you !

**Comment by mpd37** [comment] 2019-02-27 21:28
Duplicate of #206

**Comment by mpd37** [comment] 2019-02-28 00:01
line numbers will be removed now with every chapter update

**Closed by mpd37** 2019-02-28 00:01 UTC
Labels: feature request

**Comment by zhfkt** [comment] 2019-02-28 03:43
Thank you for updating. 

I checked that the chapter 3, 5, 10 have been updated. I would like to ask whether the other chapters will not be updated until there is any modification for those chapters . If there is not any modification applied on the other chapters, will we not get the version without linenums ?

**Comment by mpd37** [comment] 2019-02-28 07:28
Chapters will be updated in the next two weeks.  We will then also put a full pdf online.
