### ISSUE TITLE
Unclear notation and Wrong formula?

### ISSUE THREAD

**Issue by oliverzzm** [mml-book/mml-book.github.io#377] opened 2019-08-06 05:18 UTC
1
**Describe the mistake**
Ambiguous notation

**Location**
Please provide the 
1. 2019-07-28
2. Chapter 6
3. page 214
4. line number/equation number   equation 6.120

**Proposed solution**
What is hc(θ) Ac(γ) seperately? 

**Additional context**
Could you add more details here?

2
**Describe the mistake**
A wrong formula

**Location**
Please provide the 
1. 2019-07-28
2. Chapter 6
3. page 214
4. line number/equation number   equation 6.122

**Proposed solution**
I do my own calculation and 6.122 should be exp[γlog(μ/1-μ）+ ...] or did i do it wrong?

**Additional context**
Could you add more details here? It jumps a little bit too far.

**Comment by chengsoonong** [comment] 2019-08-06 12:07
Unfortunately, we are unable to make changes such as adding details here. 

You are free to choose the parametrization of the conjugate prior. In this example, what is probably confusing you is the fact that we chose parameters that end up looking nice in the resulting Beta distribution. And not parameters as you would expect by staring at the definition of the conjugate prior of an exponential family.

**Comment by mpd37** [comment] 2019-08-20 10:06
Duplicate of #383

**Comment by chengsoonong** [comment] 2019-08-20 11:49
We discussed this a bit more, and decided to change the parametrization.

**Closed** 2019-08-20 12:28 UTC
Labels: Chapter 6, fixed in next revision
